### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by pjiocnic** [aws-samples/aws-serverless-developer-experience-workshop-python#45]
Hi,

This link in the workshop seems to be broken - 

https://catalog.workshops.aws/serverless-developer-experience/en-US/getting-started/self-hosting#deploy-the-shared-infrastructure

It would be helpful to get access to the scripts to setup for the workshop in order to proceed further.

Thank you,
PH

**Comment by sliedig** [comment]
Apologies. We will fix this asap. Here os the page you are looking for

https://catalog.workshops.aws/serverless-developer-experience/en-US/appendix/hosting/self-hosting

**Comment by pjiocnic** [comment]
Appreciate the quick response.  Thank you!
